### ISSUE TITLE
Wrong polling station returned

### ISSUE THREAD

**Issue by PhilRumens** [DemocracyClub/UK-Polling-Stations#265]
We've noticed that the wrong polling station is returned in a few cases. Two example postcodes are

RG184NX
RG189PT

You can see the correct stations by putting the postcode in the search on http://www.westberks.gov.uk, selecting an address, and expanding "Your Councillors".

We've received complaints about this from the public, so we'll have to take your search of our site if this isn't resolved. :(

**Comment by chris48s** [comment]
Hi Phil,

First off, I'm really sorry to hear your users are having problems and that you have had complaints about this.

If we look at RG18 4NX:
http://ww2.westberks.gov.uk/InternetMapping/MyProperty.aspx?uprn=200004738234 and 
http://ww2.westberks.gov.uk/InternetMapping/MyProperty.aspx?uprn=100081027372 (for example)
you'll note that these 2 properties in the same postcode have different polling stations because the postcode crosses a polling district boundary.

With the data West Berkshire have provided (i.e: shapes representing polling districts), we aren't able to split postcodes which cross a boundary - a postcode maps to one polling district. This means in situations like this where a postcode crosses a boundary, there is necessarily a small but non-zero error rate: some of the properties in that postcode will map to the wrong polling station.

We can solve this with the right data though - some councils have provided explicit mappings of addresses/UPRNS to polling stations, which allows us to split out the addresses in postcodes which have this property. For example, if you search for CF15 7RP on http://pollingstations.democracyclub.org.uk/ - you'll get a list of addresses. 1-4 Rhymney Cottages map to one polling station and 'The Old Forge' maps to a different one.

You can read more about this in the technical specs for providing pololing station data at https://democracyclub.org.uk/projects/polling-stations/technical/ - this issue is why we recommend Address to Station lookups as the gold standard for supplying data as it ensures accuracy.

Are you able to supply us with the data in that format? If so, we can do the same for West Berkshire and solve this problem for you.

I'm a bit more confused about RG18 9PT - I've been through every address listed at http://ww2.westberks.gov.uk/InternetMapping/AddressFinder.aspx?src=snop&snop=RG189PT and they all map to "Riverside Community Centre Rosemoor Gardens Newbury RG14 2FG" - and that's where our site sends people as well: http://pollingstations.democracyclub.org.uk/postcode/RG189PT/ . Can you give any more detail on this one?

Cheers,
Chris

**Comment by PhilRumens** [comment]
We can get you the "Gold Standard" data, give us a couple of days. This should fix the problems.

Where's there's ambiguity a postcode's polling station due to the data supplied to you, it might be better to display nothing, as no information is better than incorrect information. :)

**Comment by chris48s** [comment]
Hi Phil,


> We can get you the "Gold Standard" data, give us a couple of days. This should fix the problems.

Excellent - if you chuck that over to @JoeMitchell when you've got it, we'll get that imported for you.


> Where's there's ambiguity a postcode's polling station due to the data supplied to you, it might be better to display nothing, as no information is better than incorrect information

Agreed in principle. Unfortunately, whether or not there is ambiguity is er.. ambiguous.

We're using an approach backed by data from the ONSPD and [CodePoint Open](https://www.ordnancesurvey.co.uk/business-and-government/products/code-point-open.html) datasets which doesn't allow us to know this because postcodes are represented as points rather than areas. When we look up a postcode, we get back a point representing the postcode centroid (an average of the X and Y values of all the points described by that postcode) as opposed to a list of points or a polygon. As such, if we only have district boundaries, we currently have no way of knowing whether the area described by a postcode intersects a district boundary or not - just which polling district the centroid point is inside, which is what leads to this issue :(

The best way for councils to avoid this problem is to supply addresses or UPRNs instead of district boundaries.

Cheers

**Comment by chris48s** [comment]
@PhilRumens - Cheers for providing the additional data. I've had a look at the files supplied. In the file `LLPG_polling_join` there are 36 addresses where the `PDIST` column is blank. Are you able to clarify what we should do with these?

**Comment by chris48s** [comment]
Hi @PhilRumens

I've spent some more time with the data over the weekend, and there's a few other problems that would be useful to get some clarification on:

Firstly, there are 11,316 records with no postcode. I've mostly been able to deal with this by attaching the postcodes by UPRN, although there were a 513 UPRNs which didn't appear in our copy of AddressBase (not sure if this is because some of the UPRNs supplied are terminated or because our copy of AddressBase is out of date - we have access to the March 2016 release of AddressBase if that helps). I'm comfortable with just not being able to cover those few hundred cases and showing the "we don't know - call West Berkshire council" page as we're not presenting incorrect data, just reducing coverage slightly, but in principle anything with a UPRN should have a postcode so if you're able to supply a postcode against each record then that would be really useful.

Secondly, I've got a few hundred cases in the address file where I've got duplicates of the same address with multiple different UPRNs. Here's a couple of examples:

* "58 Hunters Hill Burghfield Common Reading Berkshire" appears twice in the file with UPRNs:
  * 100080241913
  * 10090888565

* "Street Record Peasemore Newbury Berkshire" appears 11 times in the file with UPRNs:
  * 010022806748
  * 010007902510
  * 010007901596
  * 010007901836
  * 010007901887
  * 010007902593
  * 010007902783
  * 010007903332
  * 010007901763
  * 010007901309
  * 010007902381

I'm guessing the address data we've got here is probably just incomplete (my guess would be that we're missing that there's a Flat A and Flat B 58 Hunters Hill or something and we're missing house names or similar in the other case?)

This is **mostly** not too problematic, in that we can collapse the duplicates into a single record as long as every UPRN with the same address maps to the same polling district, which accounts for the majority of cases. Unfortunately we've got some cases where (even after attaching postcodes), we've got duplicates of the same address (albeit with different UPRNs) mapping to 2 different polling stations. This is going to lead to a situation where a user enters a postcode like "RG20 7EU" and we give them a choice of addresses - then, depending on whether they select the address
"Street Record Chaddleworth Newbury Berkshire" or
"Street Record Chaddleworth Newbury Berkshire"
(i.e: the same address text)
they'll be directed to different polling stations. This provides confusing user experience and doesn't really solve the problem of providing users with the wrong data that we're trying to address (no pun intended) here. I'm also not entirely convinced that "Street Record Chaddleworth Newbury Berkshire" is a useful human-readable address to present users with.

I'm happy to make some assumptions, fill in the gaps by looking up UPRNs in AddressBase where possible, or exclude problematic cases (again, better to exclude than serve incorrect data) but given your (completely valid and reasonable) concerns about providing users in West Berkshire with high quality data, I thought it would be useful to raise these issues with you in the hopes you'll be able to follow them up for us.

Let me know how you want to proceed. If it is useful for me to provide a full list of problematic cases, let me know.


td;dr - addresses are hard! :(


Thanks,
Chris

**Comment by PhilRumens** [comment]
I've raised both your queries with our IT Service who hopefully should come back with answers soon.

**Comment by PhilRumens** [comment]
From our IT Service:

LLPG contains a number of non addressable objects (streets, land etc.), so not all UPRN's have a postcode.

**Comment by chris48s** [comment]
Cheers for getting back to us Phil.

Having discussed with @symroe we think on balance this is probably best handled by the proposed fixes in PR #308 in this situation. This should solve the same problem and get round some of the problems with the data. We'll keep you in the loop.

**Comment by PhilRumens** [comment]
Will you have time to do this today or tomorrow please?

We'd like to add it to the home page of our website but can't do this until we're sure the results are reliable.

**Comment by symroe** [comment]
Yes, we're deploying it today – see the conversation in #308 if you want more on this! :)

**Comment by symroe** [comment]
`RG184NX` is showing the address picker now, so I'm considering this done!

We're still not sure about `RG189PT` – it's returning a polling station, but as per Chris's first comment above, that seems correct.
